create table if not exists public.cycle_reminders (
  id bigint generated by default as identity primary key,
  email text not null unique,
  start_date date not null,
  duration_days integer not null default 5,
  cycle_length integer not null default 28,
  reminder_days integer not null default 3,
  timezone text not null default 'UTC',
  active boolean not null default true,
  last_reminder_key text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.cycle_reminders enable row level security;
